In [146]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [147]:
ROWS = 100
df = pd.read_csv('../data/raw/kaggle/input/tweets.csv',  nrows=ROWS, low_memory = False, delimiter=';', skiprows=0, lineterminator='\n', usecols = ['timestamp','replies','likes','retweets', 'text\r'])

In [148]:
df.head()

,timestamp,replies,likes,retweets,text\r
0,2019-05-27 11:49:14+00,0,0,0,√à appena uscito un nuovo video! LES CRYPTOMONNAIES QUI PULV√âRISENT BITCOIN EN 2019 https://t.co/yCsQMvRnyS\r
1,2019-05-27 11:49:18+00,0,0,0,Cardano: Digitize Currencies; EOS https://t.co/1kTKqKEBlS 6500% ROI; AT&amp;T Bitcoin Bill Pay https://t.co/eQCwOXKHK0 | Cardano (ADA) üåèüì¢üòéü§ëüíµ | #FolloForFolloBack #follo4folloback #followforfollow #bitcointe #cryptocurrency\r
2,2019-05-27 11:49:06+00,0,2,1,Another Test tweet that wasn't caught in the stream ! bitcoin\r
3,2019-05-27 11:49:22+00,0,0,0,Current Crypto Prices! \n\nBTC: $8721.99 USD\nETH: $266.62 USD\nLTC: $114.03 USD\nBCH: $432.02 USD\nXLM: $0.133 USD\nDOGE: $ 0.00314 USD\nNEO: $12.04 USD\nXRP: $0.4092 USD\nCANN: $0.001482 USD\nEMC2: $0.1198 USD\nXMR: $94.65 USD\nBTG: $24.31 USD\r
4,2019-05-27 11:49:23+00,0,0,0,Spiv (Nosar Baz): BITCOIN Is An Asset &amp; NOT A Currency.\n\nhttps://t.co/FJru1ooxSM\n\nhttps://t.co/fYBX4H6r6r\n\nhttps://t.co/xZSjmZ0h3K\n\nhttps://t.co/v7GRFIQG7w\n\nhttps://t.co/Oq5hQt5hNn\r

In [149]:
df.tail()

,timestamp,replies,likes,retweets,text\r
95,2019-05-18 21:37:23+00,4,29,7,"@xrp_news @coinbase @APompliano I‚Äôm ‚Äòfairly‚Äô new to Crypto, so I had only transferred XRP to a couple of places. So, when I first transferred BTC it took so long that I actually thought I had ‚Äúlost‚Äù all my money... https://t.co/t8fybNlmwL\r"
96,2019-05-27 00:02:39+00,21,382,41,Keep your eye on the prize bears you got this.\n\n$BTC https://t.co/89BC3Yykjf\r
97,2019-05-27 11:50:24+00,0,0,0,(15 Great Ways for Absolute Beginners to Learn About Bitcoin (BTC)) News Aggregated By https://t.co/HdKcH29ZKZ - https://t.co/PoOebNFBMU #Crypto #cryptocurrency #Cryptonews\r
98,2019-05-27 06:31:27+00,1,76,49,"Aklƒ± olmayandan hi√ßbir ≈üey olmaz,arkada≈ülar.\n\n#DOLAR\n#DolarTL\n#bist\n#bist100 \n#usdtry\n#USDTRY\n#XU100 \n#ùí∑ùëíùìÅùëíùìÉùìàùí∂ùìé 2012\n#doge #dogeusd\n#btc #btcusd\nYTD\r"
99,2019-05-27 11:50:28+00,0,0,0,@ElizabethNoll @redditships Probably still in Bitcoin. Bought 300k and then it dropped 2/3rds in price leaving 100k. Husband has probably been holding onto it for a year going it will recover and he can put it back without ever telling her.\r

In [150]:
def dt(x):
    t = pd.Timestamp(x)
    return pd.Timestamp.date(t)

df.timestamp = df.timestamp.apply(dt)

In [151]:
df.head()

,timestamp,replies,likes,retweets,text\r
0,2019-05-27,0,0,0,√à appena uscito un nuovo video! LES CRYPTOMONNAIES QUI PULV√âRISENT BITCOIN EN 2019 https://t.co/yCsQMvRnyS\r
1,2019-05-27,0,0,0,Cardano: Digitize Currencies; EOS https://t.co/1kTKqKEBlS 6500% ROI; AT&amp;T Bitcoin Bill Pay https://t.co/eQCwOXKHK0 | Cardano (ADA) üåèüì¢üòéü§ëüíµ | #FolloForFolloBack #follo4folloback #followforfollow #bitcointe #cryptocurrency\r
2,2019-05-27,0,2,1,Another Test tweet that wasn't caught in the stream ! bitcoin\r
3,2019-05-27,0,0,0,Current Crypto Prices! \n\nBTC: $8721.99 USD\nETH: $266.62 USD\nLTC: $114.03 USD\nBCH: $432.02 USD\nXLM: $0.133 USD\nDOGE: $ 0.00314 USD\nNEO: $12.04 USD\nXRP: $0.4092 USD\nCANN: $0.001482 USD\nEMC2: $0.1198 USD\nXMR: $94.65 USD\nBTG: $24.31 USD\r
4,2019-05-27,0,0,0,Spiv (Nosar Baz): BITCOIN Is An Asset &amp; NOT A Currency.\n\nhttps://t.co/FJru1ooxSM\n\nhttps://t.co/fYBX4H6r6r\n\nhttps://t.co/xZSjmZ0h3K\n\nhttps://t.co/v7GRFIQG7w\n\nhttps://t.co/Oq5hQt5hNn\r

In [152]:
df.tail()

,timestamp,replies,likes,retweets,text\r
95,2019-05-18,4,29,7,"@xrp_news @coinbase @APompliano I‚Äôm ‚Äòfairly‚Äô new to Crypto, so I had only transferred XRP to a couple of places. So, when I first transferred BTC it took so long that I actually thought I had ‚Äúlost‚Äù all my money... https://t.co/t8fybNlmwL\r"
96,2019-05-27,21,382,41,Keep your eye on the prize bears you got this.\n\n$BTC https://t.co/89BC3Yykjf\r
97,2019-05-27,0,0,0,(15 Great Ways for Absolute Beginners to Learn About Bitcoin (BTC)) News Aggregated By https://t.co/HdKcH29ZKZ - https://t.co/PoOebNFBMU #Crypto #cryptocurrency #Cryptonews\r
98,2019-05-27,1,76,49,"Aklƒ± olmayandan hi√ßbir ≈üey olmaz,arkada≈ülar.\n\n#DOLAR\n#DolarTL\n#bist\n#bist100 \n#usdtry\n#USDTRY\n#XU100 \n#ùí∑ùëíùìÅùëíùìÉùìàùí∂ùìé 2012\n#doge #dogeusd\n#btc #btcusd\nYTD\r"
99,2019-05-27,0,0,0,@ElizabethNoll @redditships Probably still in Bitcoin. Bought 300k and then it dropped 2/3rds in price leaving 100k. Husband has probably been holding onto it for a year going it will recover and he can put it back without ever telling her.\r

In [153]:
df_price_btc = pd.read_csv('../data/raw/BitcoinPriceHistory.csv')

In [154]:
df_price_btc.Date = df_price_btc.Date.apply(dt)

In [155]:
df_price_btc.head()

         Date     Price      Open      High       Low     Vol. Change %
0  2024-04-07  69,304.0  68,897.3  69,739.7  68,849.4   41.72K    0.60%
1  2024-04-06  68,890.6  67,830.5  69,632.0  67,467.2   41.48K    1.56%
2  2024-04-05  67,830.6  68,498.7  68,692.2  66,023.3   88.97K   -0.97%
3  2024-04-04  68,496.5  65,968.4  69,238.8  65,096.3  100.30K    3.84%
4  2024-04-03  65,963.0  65,443.6  66,844.8  64,559.0   88.46K    0.80%

In [156]:
df_price_btc.tail()

            Date    Price     Open     High      Low     Vol. Change %
1950  2018-12-05  3,771.6  3,958.1  3,974.1  3,765.2  341.60K   -4.72%
1951  2018-12-04  3,958.5  3,899.9  4,082.9  3,809.3  326.71K    1.56%
1952  2018-12-03  3,897.8  4,160.3  4,177.0  3,839.9  355.10K   -6.31%
1953  2018-12-02  4,160.4  4,196.2  4,316.1  4,105.3  298.63K   -0.85%
1954  2018-12-01  4,196.2  4,038.7  4,299.1  3,967.1  316.30K    3.87%

In [157]:
df_price_btc['volume'] = df_price_btc["Vol."]
df_price_btc['variance_price'] = df_price_btc["Change %"]

In [158]:
df_price_btc = df_price_btc.drop(["Vol.", "Change %"],  axis=1, inplace=False)

In [159]:
def convert_to_float(value):
    try:
        if "K" in value.upper():
            return float(value.replace("K", ""))
        elif "%" in value.upper():
            return float(value.replace("%", ""))
        else:
            return float(value.replace(",", ""))

    except (ValueError, AttributeError):
        # Handle potential conversion errors or missing values
        return 0

In [160]:
#df_price_btc.apply(convert_to_float)
# Apply the function to 'col1'
df_price_btc["Price"] = df_price_btc["Price"].apply(convert_to_float)
df_price_btc["Open"] = df_price_btc["Open"].apply(convert_to_float)
df_price_btc["High"] = df_price_btc["High"].apply(convert_to_float)
df_price_btc["Low"] = df_price_btc["Low"].apply(convert_to_float)
df_price_btc["volume"] = df_price_btc["volume"].apply(convert_to_float)
df_price_btc["variance_price"] = df_price_btc["variance_price"].apply(convert_to_float)
df_price_btc.head()

         Date    Price     Open     High      Low  volume  variance_price
0  2024-04-07  69304.0  68897.3  69739.7  68849.4   41.72            0.60
1  2024-04-06  68890.6  67830.5  69632.0  67467.2   41.48            1.56
2  2024-04-05  67830.6  68498.7  68692.2  66023.3   88.97           -0.97
3  2024-04-04  68496.5  65968.4  69238.8  65096.3  100.30            3.84
4  2024-04-03  65963.0  65443.6  66844.8  64559.0   88.46            0.80

In [161]:
df_price_btc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1955 entries, 0 to 1954
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            1955 non-null   object
 1   Price           1955 non-null   float64
 2   Open            1955 non-null   float64
 3   High            1955 non-null   float64
 4   Low             1955 non-null   float64
 5   volume          1955 non-null   float64
 6   variance_price  1955 non-null   float64
dtypes: float64(6), object(1)
memory usage: 107.0+ KB

In [162]:
#criando campo de data nos dois datasets antes de uni-los
df['date'] = df.timestamp
df_price_btc['date'] = df_price_btc.Date
# Definindo a coluna de chave prim√°ria (assumindo que ambas possuem 'data')
key = 'date'
# Realizando a jun√ß√£o interna
df_origin = df_price_btc.merge(df, on=key, how='inner')

df_origin.head()

,Date,Price,Open,High,Low,volume,variance_price,date,timestamp,replies,likes,retweets,text\r
0,2019-05-27,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,2019-05-27,0,0,0,√à appena uscito un nuovo video! LES CRYPTOMONNAIES QUI PULV√âRISENT BITCOIN EN 2019 https://t.co/yCsQMvRnyS\r
1,2019-05-27,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,2019-05-27,0,0,0,Cardano: Digitize Currencies; EOS https://t.co/1kTKqKEBlS 6500% ROI; AT&amp;T Bitcoin Bill Pay https://t.co/eQCwOXKHK0 | Cardano (ADA) üåèüì¢üòéü§ëüíµ | #FolloForFolloBack #follo4folloback #followforfollow #bitcointe #cryptocurrency\r
2,2019-05-27,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,2019-05-27,0,2,1,Another Test tweet that wasn't caught in the stream ! bitcoin\r
3,2019-05-27,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,2019-05-27,0,0,0,Current Crypto Prices! \n\nBTC: $8721.99 USD\nETH: $266.62 USD\nLTC: $114.03 USD\nBCH: $432.02 USD\nXLM: $0.133 USD\nDOGE: $ 0.00314 USD\nNEO: $12.04 USD\nXRP: $0.4092 USD\nCANN: $0.001482 USD\nEMC2: $0.1198 USD\nXMR: $94.65 USD\nBTG: $24.31 USD\r
4,2019-05-27,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,2019-05-27,0,0,0,Spiv (Nosar Baz): BITCOIN Is An Asset &amp; NOT A Currency.\n\nhttps://t.co/FJru1ooxSM\n\nhttps://t.co/fYBX4H6r6r\n\nhttps://t.co/xZSjmZ0h3K\n\nhttps://t.co/v7GRFIQG7w\n\nhttps://t.co/Oq5hQt5hNn\r

In [163]:
df_origin = df_origin.drop(['Date', 'timestamp'], axis=1, inplace=False)

In [164]:

df_origin.columns = df_origin.columns.str.lower()

df_origin.head()

,price,open,high,low,volume,variance_price,date,replies,likes,retweets,text\r
0,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,0,0,0,√à appena uscito un nuovo video! LES CRYPTOMONNAIES QUI PULV√âRISENT BITCOIN EN 2019 https://t.co/yCsQMvRnyS\r
1,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,0,0,0,Cardano: Digitize Currencies; EOS https://t.co/1kTKqKEBlS 6500% ROI; AT&amp;T Bitcoin Bill Pay https://t.co/eQCwOXKHK0 | Cardano (ADA) üåèüì¢üòéü§ëüíµ | #FolloForFolloBack #follo4folloback #followforfollow #bitcointe #cryptocurrency\r
2,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,0,2,1,Another Test tweet that wasn't caught in the stream ! bitcoin\r
3,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,0,0,0,Current Crypto Prices! \n\nBTC: $8721.99 USD\nETH: $266.62 USD\nLTC: $114.03 USD\nBCH: $432.02 USD\nXLM: $0.133 USD\nDOGE: $ 0.00314 USD\nNEO: $12.04 USD\nXRP: $0.4092 USD\nCANN: $0.001482 USD\nEMC2: $0.1198 USD\nXMR: $94.65 USD\nBTG: $24.31 USD\r
4,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,0,0,0,Spiv (Nosar Baz): BITCOIN Is An Asset &amp; NOT A Currency.\n\nhttps://t.co/FJru1ooxSM\n\nhttps://t.co/fYBX4H6r6r\n\nhttps://t.co/xZSjmZ0h3K\n\nhttps://t.co/v7GRFIQG7w\n\nhttps://t.co/Oq5hQt5hNn\r

In [165]:
df_origin.head()

,price,open,high,low,volume,variance_price,date,replies,likes,retweets,text\r
0,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,0,0,0,√à appena uscito un nuovo video! LES CRYPTOMONNAIES QUI PULV√âRISENT BITCOIN EN 2019 https://t.co/yCsQMvRnyS\r
1,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,0,0,0,Cardano: Digitize Currencies; EOS https://t.co/1kTKqKEBlS 6500% ROI; AT&amp;T Bitcoin Bill Pay https://t.co/eQCwOXKHK0 | Cardano (ADA) üåèüì¢üòéü§ëüíµ | #FolloForFolloBack #follo4folloback #followforfollow #bitcointe #cryptocurrency\r
2,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,0,2,1,Another Test tweet that wasn't caught in the stream ! bitcoin\r
3,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,0,0,0,Current Crypto Prices! \n\nBTC: $8721.99 USD\nETH: $266.62 USD\nLTC: $114.03 USD\nBCH: $432.02 USD\nXLM: $0.133 USD\nDOGE: $ 0.00314 USD\nNEO: $12.04 USD\nXRP: $0.4092 USD\nCANN: $0.001482 USD\nEMC2: $0.1198 USD\nXMR: $94.65 USD\nBTG: $24.31 USD\r
4,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,0,0,0,Spiv (Nosar Baz): BITCOIN Is An Asset &amp; NOT A Currency.\n\nhttps://t.co/FJru1ooxSM\n\nhttps://t.co/fYBX4H6r6r\n\nhttps://t.co/xZSjmZ0h3K\n\nhttps://t.co/v7GRFIQG7w\n\nhttps://t.co/Oq5hQt5hNn\r

In [166]:
text = list(df_origin.loc[:,'text\r'].values)

In [167]:
from transformers import AutoTokenizer ,pipeline
from transformers import TFAutoModelForSequenceClassification

finbert = TFAutoModelForSequenceClassification.from_pretrained("../models/ProsusAI-finbert")
tokenizer = AutoTokenizer.from_pretrained("../models/ProsusAI-finbert")
classifier = pipeline('sentiment-analysis', model=finbert, tokenizer=tokenizer)

All model checkpoint layers were used when initializing TFBertForSequenceClassification.

Some layers of TFBertForSequenceClassification were not initialized from the model checkpoint at ../models/ProsusAI-finbert and are newly initialized: ['classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [168]:
label_and_score = classifier(text)
labels =[pred['label'] for pred in label_and_score]
labels = list(map(lambda x: x.replace('positive','1'), labels))
labels = list(map(lambda x: x.replace('neutral','0'), labels))
labels = list(map(lambda x: x.replace('negative','-1'), labels))
labels = list(map(int, labels))
df_origin.loc[:,'label'] = labels

In [169]:
df_origin.head()

,price,open,high,low,volume,variance_price,date,replies,likes,retweets,text\r,label
0,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,0,0,0,√à appena uscito un nuovo video! LES CRYPTOMONNAIES QUI PULV√âRISENT BITCOIN EN 2019 https://t.co/yCsQMvRnyS\r,-1
1,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,0,0,0,Cardano: Digitize Currencies; EOS https://t.co/1kTKqKEBlS 6500% ROI; AT&amp;T Bitcoin Bill Pay https://t.co/eQCwOXKHK0 | Cardano (ADA) üåèüì¢üòéü§ëüíµ | #FolloForFolloBack #follo4folloback #followforfollow #bitcointe #cryptocurrency\r,-1
2,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,0,2,1,Another Test tweet that wasn't caught in the stream ! bitcoin\r,-1
3,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,0,0,0,Current Crypto Prices! \n\nBTC: $8721.99 USD\nETH: $266.62 USD\nLTC: $114.03 USD\nBCH: $432.02 USD\nXLM: $0.133 USD\nDOGE: $ 0.00314 USD\nNEO: $12.04 USD\nXRP: $0.4092 USD\nCANN: $0.001482 USD\nEMC2: $0.1198 USD\nXMR: $94.65 USD\nBTG: $24.31 USD\r,-1
4,8760.1,8628.9,8902.8,8607.3,907.96,1.51,2019-05-27,0,0,0,Spiv (Nosar Baz): BITCOIN Is An Asset &amp; NOT A Currency.\n\nhttps://t.co/FJru1ooxSM\n\nhttps://t.co/fYBX4H6r6r\n\nhttps://t.co/xZSjmZ0h3K\n\nhttps://t.co/v7GRFIQG7w\n\nhttps://t.co/Oq5hQt5hNn\r,-1

In [170]:
df_origin.tail()

,price,open,high,low,volume,variance_price,date,replies,likes,retweets,text\r,label
94,6386.0,6194.3,6466.6,6157.8,907.94,3.14,2019-05-10,0,0,0,@mark_dow Bitcoin is the one imv\r,-1
95,6386.0,6194.3,6466.6,6157.8,907.94,3.14,2019-05-10,0,0,1,Bitcoin FUDsters RN https://t.co/Yxo3TCxQci\r,-1
96,6386.0,6194.3,6466.6,6157.8,907.94,3.14,2019-05-10,0,0,0,"@KennETHbosak ""Banking on Bitcoin"" on Netflix.\r",-1
97,5493.8,5384.6,5530.8,5370.0,722.23,2.04,2019-05-02,6,282,85,https://t.co/Ip0ph8uZYn\n\n#cryptocurrency #drife #blockchain #crypto #eos #eth #ethereum #btc #cabs #taxi #ride #rides\r,-1
98,3886.0,3870.3,3900.1,3817.1,0.00,0.41,2019-03-12,1,0,1,#Bitcoin #Satoshi #crypto #blockchain #Airdrop\nNew Airdrop #Idap üì¢\n\nIdap Round 3 airdrop is worth 200 #IDAP and 200 #IDAP by referral ‚úàÔ∏èüí∞\n\n1. Sign up Here : https://t.co/HHixVAi42h üöÄ\n\n2. Verify your Email\n\n3. +200 #IDAP by ref https://t.co/0b8MgKDve1\r,1